name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Cache gem dependencies
        uses: actions/cache@v1
        with:
          path: server/vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-bundler-

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install libsqlite3-dev

          cd server
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Rails specs
        env:
          RAILS_ENV: test
        run: |
          cd server
          bin/rails db:create
          bin/rails db:schema:load
          bin/rails spec
